spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurantdb
    username: root
    password: Test$_$123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false